### ISSUE TITLE
Guidance?

### ISSUE THREAD

**Issue by malachib** [ubiety/Ubiety.Xmpp.Core#12]
Your lib looks quite promising ~
Any documentation for guidance how to use it?  Thank you!

**Comment by coder2000** [comment]
It is still in the beginning stages and while a good starting point still needs a lot of work. You can find a more complete version at https://github.com/ubiety/xmpp however it is only .NET Framework.

The Ubiety.XMPP.App project in the src folder should provide some basic introduction to the direction the library will take.
